import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'builder-camp',
      label: 'Builder Camp',
    },
    {
      type: 'category',
      label: 'Divvi Protocol',
      items: [
        'protocol/overview',
        'protocol/frontends',
        'protocol/fund-managers',
      ],
    },
    {
      type: 'category',
      label: 'Mobile Framework',
      items: [
        'mobile-framework/overview',
        {
          type: 'category',
          label: 'Creating a new project',
          items: [
            {
              type: 'autogenerated',
              dirName: 'mobile-framework/divvi-mobile', // Generate sidebar slice from docs/mobile-framework/divvi-mobile
            },
          ],
        },
        {
          type: 'category',
          label: 'Adding a backend protocol',
          items: [
            {
              type: 'autogenerated',
              dirName: 'hooks', // Generate sidebar slice from docs/hooks
            },
          ],
        },
        {
          type: 'category',
          label: 'Publishing',
          items: [
            'publishing/play-store',
            'publishing/app-store',
            'publishing/asset-requirements',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'GTM Playbook',
      items: [
        'gtm/introduction',
        'gtm/positioning',
        'gtm/strategy',
        'gtm/execution',
      ],
    },
  ],
}

export default sidebars
